### PR TITLE
library ic-classes.h

### PR DESCRIPTION
**Pull request by karlillacg**
Hi dear friends,
I've tried to compile the example code TSL1401.ino, but I had the error in library ic-classes.h in TSLXX.cpp
Could you, please, help me? I'm really really lost :'(  I have used all the codes and made my own modifications and ca't get reasonable values.

Thank you a lot

### CODE REVIEW

**Comment by hobgreenson** [comment]
Hi there,

I would suggest submitting this pull request to tobiasvogel because he made a huge number of additions to this code and I no longer maintain this repo.

Cheers,
Matt

**Comment by karlillacg** [comment]
Thank you, I will. Could you please send me his mail?

2017-03-09 14:18 GMT-06:00 Matthew Green <notifications@github.com>:

**Comment by hobgreenson** [comment]
I don't know it, this is his github profile: https://github.com/tobiasvogel

good luck!

**Comment by karlillacg** [comment]
thank you very much :)

2017-03-09 14:32 GMT-06:00 Matthew Green <notifications@github.com>:

**Pull request closed without merging**
